<?php

/**
 * @file
 * qma_interface.install
 */


/**
 * Implements hook_install().
 */
function qma_interface_install() {
  
}

/**
 * Sets the weight of qma_interface to be heavier than drupagram.
 * This is necessary to override hook_admin_paths_alter().
 */
function qma_interface_update_7001(&$sandbox) {
  db_update('system')
    ->fields(array(
      'weight' => 4,
    ))
    ->condition('type', 'module')
    ->condition('name', 'qma_interface')
    ->execute();
}
